version: '3'

services:

  db:
    image: mongo
    ports:
      - '27017:27017'

  web:
    build: .
    command: python app.py
    volumes:
      - .:/app
    ports:
      - '5000:5000'
    links:
      - db
    depends_on:
      - db
